### ISSUE TITLE
no equivalent to Rendering Mode: "Fade", "Cutout" and "Transparent"

### ISSUE THREAD

**Issue by SupraLP** [Xiexe/Xiexes-Unity-Shaders#4]
![xiexe_toon_sample](https://user-images.githubusercontent.com/31988415/45915961-7ee5e900-be5e-11e8-8ac9-8972887f524f.PNG)
![cubed_flat_lit_toon_sample](https://user-images.githubusercontent.com/31988415/45915962-81e0d980-be5e-11e8-891d-b3d79f961941.PNG)

**Comment by Xiexe** [comment]
Use the included Shader Generator to generate the variants. 

They need to be split into multiple shaders for various reasons due to VRChat not handling overriding sorting tags via an editor script - and I needed to cut down on initial import times. 

You can find the shader generator under Xiexe > Tools > Shader Generator.
